In [1]:
from olist_utils import run_query, set_style, COLORS
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

set_style()

run_query("SELECT COUNT(*) AS n FROM dwd_orders")

       n
0  99441

恒等式校验：
检查approve_days seller_days transit_days 三者不为NULL的订单中, 加起来等于delivery_days的比例

In [2]:
sql = """
SELECT SUM(CASE WHEN approve_days + seller_days + transit_days = delivery_days THEN 1 END) AS right_time, 
       AVG(CASE WHEN approve_days + seller_days + transit_days = delivery_days THEN 1 ELSE 0 END) AS rate_right
FROM dws_order_fulfillment
WHERE approve_days IS NOT NULL AND seller_days IS NOT NULL AND transit_days IS NOT NULL
"""
df = run_query(sql)
df

   right_time  rate_right
0     95498.0         1.0

查看订单距离

In [3]:
# 最大订单距离
sql_max_dis = """
SELECT MAX(distance_km) 
FROM dws_order_fulfillment;
"""
run_query(sql_max_dis)

   MAX(distance_km)
0            8677.9

In [4]:
#查询距离超过4500KM的订单数
sql = """
SELECT COUNT(*) AS dis_big_than_4500
FROM dws_order_fulfillment
WHERE distance_km > 4500;
"""
run_query(sql)

   dis_big_than_4500
0                  4